import java.awt.HeadlessException;
import java.sql.*;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

public class FormSewaKomputer extends javax.swing.JInternalFrame {
  private JSpinner.DateEditor editor1;
  private JSpinner.DateEditor editor2;
  public static Connection koneksi;
  public static Statement st;
  public static ResultSet rs;
  
    public FormSewaKomputer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNama = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        labelJenisKomputer = new javax.swing.JLabel();
        cbJenisLaptop = new javax.swing.JComboBox<>();
        labelTanggalSewa = new javax.swing.JLabel();
        labelTanggalKembali = new javax.swing.JLabel();
        btnSewaKomputer = new javax.swing.JButton();
        tanggalSewa = new javax.swing.JSpinner();
        tanggalKembali = new javax.swing.JSpinner();

        setTitle("Form Sewa Komputer");
        setPreferredSize(new java.awt.Dimension(700, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        labelNama.setText("Nama");

        labelJenisKomputer.setText("Jenis Komputer");

        cbJenisLaptop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lenovo", "Asus", "Toshiba", "Macbook", "HP", "Dell" }));
        cbJenisLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisLaptopActionPerformed(evt);
            }
        });

        labelTanggalSewa.setText("Tanggal Sewa");

        labelTanggalKembali.setText("Tanggal Kembali");

        btnSewaKomputer.setText("Sewa Komputer");
        btnSewaKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSewaKomputerActionPerformed(evt);
            }
        });

        tanggalSewa.setModel(new javax.swing.SpinnerDateModel());

        tanggalKembali.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTanggalSewa)
                            .addComponent(labelJenisKomputer)
                            .addComponent(labelNama))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJenisLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSewaKomputer)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelTanggalKembali)
                            .addGap(22, 22, 22)
                            .addComponent(tanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJenisKomputer)
                    .addComponent(cbJenisLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggalSewa)
                    .addComponent(tanggalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggalKembali)
                    .addComponent(tanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSewaKomputer)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        editor1 = new JSpinner.DateEditor(tanggalSewa, "yyyy-MM-dd");
        editor2 = new JSpinner.DateEditor(tanggalKembali, "yyyy-MM-dd");
        tanggalSewa.setEditor(editor1);
        tanggalKembali.setEditor(editor2); 
        
        try {
            String database = "jdbc:mysql://localhost/UASBondan";
            String user = "root";
            String pass = "password";
            Class.forName("com.mysql.jdbc.Driver");
            koneksi = DriverManager.getConnection(database, user, pass);
            
            st = koneksi.createStatement();
            System.out.println("Koneksi berhasil.");
        }
        
        catch (SQLException ex) {
            
        } catch (ClassNotFoundException ex) { 
            System.out.println("Error class not found.");
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSewaKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSewaKomputerActionPerformed
        // Membuat variable untuk menyimpan nama dan jenis laptop yang diinputkan oleh pengguna
        String nama = fieldNama.getText();
        String jenisLaptop = cbJenisLaptop.getSelectedItem().toString();
   
        int harga = 0;
        
        switch(jenisLaptop) {
            case "Lenovo":
                harga = 100000;
                break;
            case "Asus":
                harga = 95000;
                break;
            case "Toshiba":
                harga = 90000;
                break;
            case "Macbook":
                harga = 120000;
                break;
            case "HP":
                harga = 102000;
                break;
            case "Dell":
                harga = 105000;
                break;
        }
        
        // String untuk menyesuaikan format tanggal pada mySQL
        String tglSewa = editor1.getFormat().format(tanggalSewa.getValue());
        String tglKembali = editor2.getFormat().format(tanggalKembali.getValue());
        
        // String tersebut diubah ke localdate agar dapat digunakan oleh method ChronoUnit.Days.between.
        // ChronoUnit.Days.between digunakan untuk menghitung jumlah hari di antara dua tanggal.
	LocalDate tglSewaParsed = LocalDate.parse(tglSewa);
	LocalDate tglKembaliParsed = LocalDate.parse(tglKembali);
        
	long jumlahHari = ChronoUnit.DAYS.between(tglSewaParsed, tglKembaliParsed);
        
        int totalHarga = (int)((jumlahHari+1) * harga);  
      
        String query = "insert into sewakomputer (nama, jenis_laptop, harga_sewa_harian, tanggal_sewa, tanggal_kembali, total_harga) values ('" + nama + "', '" + jenisLaptop +    "', '" + harga + "', '" + tglSewa +"', '" + tglKembali + "', '" + totalHarga + "')";
        
        try {
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            fieldNama.setText("");
            cbJenisLaptop.setSelectedIndex(0);
        }
        catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, " data error " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSewaKomputerActionPerformed

    private void cbJenisLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisLaptopActionPerformed

    }//GEN-LAST:event_cbJenisLaptopActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSewaKomputer;
    private javax.swing.JComboBox<String> cbJenisLaptop;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JLabel labelJenisKomputer;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTanggalKembali;
    private javax.swing.JLabel labelTanggalSewa;
    private javax.swing.JSpinner tanggalKembali;
    private javax.swing.JSpinner tanggalSewa;
    // End of variables declaration//GEN-END:variables
}
