import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TabelSewaKomputer extends javax.swing.JInternalFrame {
    public static Connection koneksi;
    public static Statement st;
    public static ResultSet rs;
    /**
     * Creates new form TabelSewaKomputer
     */
    public TabelSewaKomputer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSewaKomputer = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();

        setTitle("Tabel Sewa Komputer");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tabelSewaKomputer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Laptop", "Harga Sewa Harian", "Tanggal Sewa", "Tanggal Kembali", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(tabelSewaKomputer);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            String database = "jdbc:mysql://localhost/UASBondan";
            String user = "root";
            String pass = "password";
            Class.forName("com.mysql.jdbc.Driver");
            koneksi = DriverManager.getConnection(database, user, pass);
            
            st = koneksi.createStatement();
            System.out.println("Koneksi berhasil.");
            
            rs = st.executeQuery("select * from sewakomputer");
            DefaultTableModel tbl = (DefaultTableModel)tabelSewaKomputer.getModel();
            tbl.setNumRows(0);
            
            while(rs.next())
            {
                tbl.addRow(new Object[] {
                    rs.getString("No"),
                    rs.getString("Nama"),
                    rs.getString("Jenis_Laptop"),
                    rs.getString("Harga_Sewa_Harian"),
                    rs.getString("Tanggal_Sewa"),
                    rs.getString("Tanggal_Kembali"),
                    rs.getString("Total_Harga")
                });
            }
        }
        
        catch (SQLException ex) {
            
        } catch (ClassNotFoundException ex) { 
            System.out.println("Error class not found.");
        }
    }//GEN-LAST:event_formComponentShown

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        String query = "truncate sewakomputer;";
        
        try {
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Data berhasil direset!");
            DefaultTableModel tbl = (DefaultTableModel)tabelSewaKomputer.getModel();
            tbl.setNumRows(0);
        }
        
        catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelSewaKomputer;
    // End of variables declaration//GEN-END:variables
}
